# The route for handling newsletter subscription requests
newsletter_subscribe:
    path: /newsletter/subscribe
    controller: App\Bundle\NewsletterBundle\Controller\NewsletterController::subscribe
    methods: [POST]
    defaults:
        _route: newsletter_subscribe

# The route for confirming newsletter subscriptions
newsletter_confirm:
    path: /newsletter/confirm
    controller: App\Bundle\NewsletterBundle\Controller\NewsletterController::confirm
    defaults:
        _route: newsletter_confirm
